### ISSUE TITLE
Passing an alternative PDK image does not work

### ISSUE THREAD

**Issue by fraenki** [puppets-epic-show-theatre/action-pdk-validate#4]
So I've tried to use the pdk "nightly" image...

```
       - name: Run pdk validate
         uses: puppets-epic-show-theatre/action-pdk-validate@v1.1.0
         with:
           pdk-image: puppet/pdk:nightly
           puppet-version: ${{ matrix.puppet_version }}
```

...but unfortunately, the GitHub Action still uses the "latest" image. From the GitHub Actions logs:

```
...
Download action repository 'puppets-epic-show-theatre/action-pdk-validate@v1.1.0' (SHA:4536bf103a3c2b92ddee02dfceab99a27ef2e83f)
...
Build container for action use: '/home/runner/work/_actions/puppets-epic-show-theatre/action-pdk-validate/v1.1.0/Dockerfile'.
  /usr/bin/docker build -t a5c76b:ebfbbc0bea1d492c8f1f5190da4765ee -f "/home/runner/work/_actions/puppets-epic-show-theatre/action-pdk-validate/v1.1.0/Dockerfile" "/home/runner/work/_actions/puppets-epic-show-theatre/action-pdk-validate/v1.1.0"
Sending build context to Docker daemon  41.98kB
  
Step 1/5 : ARG PDKIMAGE=puppet/pdk:latest
Step 2/5 : FROM $PDKIMAGE
latest: Pulling from puppet/pdk
...
```

So it looks like that `pdk-image` parameter does nothing. Or am I doing something wrong?
